name: tcodeの辞書で何げに変換できないものの報告
description: tcodeの辞書で何げに変換できないものの改善をGitHub issue formで行う
title: "[tcode-dict]: REPLACE ME"
labels: [tcode-dict]
assignees:
  - naota
body:
  - type: markdown
    attributes:
      value: |
        ここに何が変換できなかったか書いてください。
    validations:
      required: true
