name: tcodeの辞書で何げに変換できないものの報告
description: tcodeの辞書で何げに変換できないものの改善をGitHub issue formで行う
title: "[tcode-dict]: REPLACE ME"
labels: [tcode-dict]
assignees:
  - naota
body:
  - type: markdown
    attributes:
      value: |
        このissueでtcodeの辞書で何が変換できなかったかの情報を共有してください。
  - type: textarea
    id: cannot-convert-dict
    attributes:
      label: dict
      description: 何が変換できなかったか
      placeholder: Tell us your conversion!
      value: "「何が変換できなかったか」に置き換えてください。"
    validations:
      required: true
